/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FlowCompleteEvent, FlowErrorEvent, StepChangeEvent } from "./store/interfaces";
import { ButtonSize, ButtonVariant } from "./components/ui/ui-button/ui-button";
import { CarouselBreakpoint } from "./components/ui/ui-carousel/ui-carousel";
import { InputType } from "./components/ui/ui-input/ui-input";
import { SelectOption } from "./components/ui/ui-select/ui-select";
export { FlowCompleteEvent, FlowErrorEvent, StepChangeEvent } from "./store/interfaces";
export { ButtonSize, ButtonVariant } from "./components/ui/ui-button/ui-button";
export { CarouselBreakpoint } from "./components/ui/ui-carousel/ui-carousel";
export { InputType } from "./components/ui/ui-input/ui-input";
export { SelectOption } from "./components/ui/ui-select/ui-select";
export namespace Components {
    interface FixedServiceFlow {
        /**
          * Base URL for the API
         */
        "apiUrl": string;
        /**
          * Optional correlation ID for tracking
         */
        "correlationId"?: string;
        /**
          * Debug mode
          * @default false
         */
        "debug"?: boolean;
        /**
          * Google Maps API Key
         */
        "googleMapsKey": string;
        /**
          * Initial step (default: 1)
          * @default 1
         */
        "initialStep"?: FlowStep;
    }
    interface StepCatalogue {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepConfirmation {
        "onBack": () => void;
        "onCancel": () => void;
        "onComplete": (event: FlowCompleteEvent) => void;
    }
    interface StepContract {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepForm {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepLocation {
        "googleMapsKey": string;
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepOrderSummary {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepPayment {
        "onBack": () => void;
        "onNext": () => void;
        "paymentIframeUrl"?: string;
    }
    interface StepPlans {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepProductDetail {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface StepShipping {
        "onBack": () => void;
        "onNext": () => void;
    }
    interface UiButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Full width button
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Loading state (shows spinner)
          * @default false
         */
        "loading": boolean;
        /**
          * Button size
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * Button type attribute
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant style
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface UiCarousel {
        /**
          * Auto-play interval in milliseconds (0 = disabled)
          * @default 0
         */
        "autoplay": number;
        /**
          * Responsive breakpoints Default: mobile=1, tablet=2, desktop=3, large=4
          * @default [     { minWidth: 0, slidesPerView: 1 },     { minWidth: 600, slidesPerView: 2 },     { minWidth: 900, slidesPerView: 3 },     { minWidth: 1200, slidesPerView: 4 },   ]
         */
        "breakpoints": CarouselBreakpoint[];
        /**
          * Gap between slides in pixels
          * @default 16
         */
        "gap": number;
        /**
          * Enable loop/circular mode
          * @default false
         */
        "loop": boolean;
        /**
          * Show navigation arrows
          * @default true
         */
        "showNavigation": boolean;
        /**
          * Show pagination dots
          * @default true
         */
        "showPagination": boolean;
        /**
          * Default number of slides per view
          * @default 1
         */
        "slidesPerView": number;
        /**
          * Total number of items in the carousel
          * @default 0
         */
        "totalItems": number;
    }
    interface UiCheckbox {
        /**
          * The checkbox value
          * @default false
         */
        "checked": boolean;
        /**
          * Whether the checkbox is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message to display
          * @default ''
         */
        "errorMessage": string;
        /**
          * Whether the checkbox has an error
          * @default false
         */
        "hasError": boolean;
        /**
          * The checkbox label
          * @default ''
         */
        "label": string;
        /**
          * The checkbox name
          * @default ''
         */
        "name": string;
    }
    interface UiDatePicker {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message to display
         */
        "error"?: string;
        /**
          * Helper text below the input
         */
        "helperText"?: string;
        /**
          * Input label
         */
        "label"?: string;
        /**
          * Maximum date (YYYY-MM-DD)
         */
        "max"?: string;
        /**
          * Minimum date (YYYY-MM-DD)
         */
        "min"?: string;
        /**
          * Input name attribute
         */
        "name"?: string;
        /**
          * Placeholder text
          * @default 'dd/mm/yyyy'
         */
        "placeholder"?: string;
        /**
          * Read-only state
          * @default false
         */
        "readonly": boolean;
        /**
          * Required field
          * @default false
         */
        "required": boolean;
        /**
          * Current value (YYYY-MM-DD format)
          * @default ''
         */
        "value": string;
    }
    interface UiInput {
        /**
          * Autocomplete attribute
         */
        "autocomplete"?: string;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message to display
         */
        "error"?: string;
        /**
          * Helper text (shown when no error)
         */
        "helperText"?: string;
        /**
          * Input label text
         */
        "label"?: string;
        /**
          * Maximum length
         */
        "maxlength"?: number;
        /**
          * Minimum length
         */
        "minlength"?: number;
        /**
          * Input name attribute
         */
        "name"?: string;
        /**
          * Input pattern for validation
         */
        "pattern"?: string;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Read-only state
          * @default false
         */
        "readonly": boolean;
        /**
          * Required field
          * @default false
         */
        "required": boolean;
        /**
          * Input type
          * @default 'text'
         */
        "type": InputType;
        /**
          * Current value
          * @default ''
         */
        "value": string;
    }
    interface UiRadio {
        /**
          * Whether this radio is selected
          * @default false
         */
        "checked": boolean;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Radio label text
         */
        "label"?: string;
        /**
          * Radio name (for grouping)
         */
        "name": string;
        /**
          * Radio value
         */
        "value": string;
    }
    interface UiRadioCard {
        /**
          * Badge text (optional, e.g., "Recomendado")
         */
        "badge"?: string;
        /**
          * Card title
         */
        "cardTitle"?: string;
        /**
          * Whether this card is selected
          * @default false
         */
        "checked": boolean;
        /**
          * Card description
         */
        "description"?: string;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Icon name or URL (optional)
         */
        "icon"?: string;
        /**
          * Radio name (for grouping)
         */
        "name": string;
        /**
          * Price to display (optional)
         */
        "price"?: string;
        /**
          * Radio value
         */
        "value": string;
    }
    interface UiSelect {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message to display
         */
        "error"?: string;
        /**
          * Select label text
         */
        "label"?: string;
        /**
          * Select name attribute
         */
        "name"?: string;
        /**
          * Options array
          * @default []
         */
        "options": SelectOption[];
        /**
          * Placeholder text
          * @default 'Seleccionar'
         */
        "placeholder"?: string;
        /**
          * Required field
          * @default false
         */
        "required": boolean;
        /**
          * Current selected value
          * @default ''
         */
        "value": string;
    }
}
export interface FixedServiceFlowCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFixedServiceFlowElement;
}
export interface UiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiButtonElement;
}
export interface UiCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiCheckboxElement;
}
export interface UiDatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiDatePickerElement;
}
export interface UiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiInputElement;
}
export interface UiRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiRadioElement;
}
export interface UiRadioCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiRadioCardElement;
}
export interface UiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiSelectElement;
}
declare global {
    interface HTMLFixedServiceFlowElementEventMap {
        "flowComplete": FlowCompleteEvent;
        "flowError": FlowErrorEvent;
        "flowCancel": void;
        "stepChange": StepChangeEvent;
    }
    interface HTMLFixedServiceFlowElement extends Components.FixedServiceFlow, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFixedServiceFlowElementEventMap>(type: K, listener: (this: HTMLFixedServiceFlowElement, ev: FixedServiceFlowCustomEvent<HTMLFixedServiceFlowElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFixedServiceFlowElementEventMap>(type: K, listener: (this: HTMLFixedServiceFlowElement, ev: FixedServiceFlowCustomEvent<HTMLFixedServiceFlowElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFixedServiceFlowElement: {
        prototype: HTMLFixedServiceFlowElement;
        new (): HTMLFixedServiceFlowElement;
    };
    interface HTMLStepCatalogueElement extends Components.StepCatalogue, HTMLStencilElement {
    }
    var HTMLStepCatalogueElement: {
        prototype: HTMLStepCatalogueElement;
        new (): HTMLStepCatalogueElement;
    };
    interface HTMLStepConfirmationElement extends Components.StepConfirmation, HTMLStencilElement {
    }
    var HTMLStepConfirmationElement: {
        prototype: HTMLStepConfirmationElement;
        new (): HTMLStepConfirmationElement;
    };
    interface HTMLStepContractElement extends Components.StepContract, HTMLStencilElement {
    }
    var HTMLStepContractElement: {
        prototype: HTMLStepContractElement;
        new (): HTMLStepContractElement;
    };
    interface HTMLStepFormElement extends Components.StepForm, HTMLStencilElement {
    }
    var HTMLStepFormElement: {
        prototype: HTMLStepFormElement;
        new (): HTMLStepFormElement;
    };
    interface HTMLStepLocationElement extends Components.StepLocation, HTMLStencilElement {
    }
    var HTMLStepLocationElement: {
        prototype: HTMLStepLocationElement;
        new (): HTMLStepLocationElement;
    };
    interface HTMLStepOrderSummaryElement extends Components.StepOrderSummary, HTMLStencilElement {
    }
    var HTMLStepOrderSummaryElement: {
        prototype: HTMLStepOrderSummaryElement;
        new (): HTMLStepOrderSummaryElement;
    };
    interface HTMLStepPaymentElement extends Components.StepPayment, HTMLStencilElement {
    }
    var HTMLStepPaymentElement: {
        prototype: HTMLStepPaymentElement;
        new (): HTMLStepPaymentElement;
    };
    interface HTMLStepPlansElement extends Components.StepPlans, HTMLStencilElement {
    }
    var HTMLStepPlansElement: {
        prototype: HTMLStepPlansElement;
        new (): HTMLStepPlansElement;
    };
    interface HTMLStepProductDetailElement extends Components.StepProductDetail, HTMLStencilElement {
    }
    var HTMLStepProductDetailElement: {
        prototype: HTMLStepProductDetailElement;
        new (): HTMLStepProductDetailElement;
    };
    interface HTMLStepShippingElement extends Components.StepShipping, HTMLStencilElement {
    }
    var HTMLStepShippingElement: {
        prototype: HTMLStepShippingElement;
        new (): HTMLStepShippingElement;
    };
    interface HTMLUiButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiButtonElementEventMap>(type: K, listener: (this: HTMLUiButtonElement, ev: UiButtonCustomEvent<HTMLUiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiButtonElementEventMap>(type: K, listener: (this: HTMLUiButtonElement, ev: UiButtonCustomEvent<HTMLUiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCarouselElement extends Components.UiCarousel, HTMLStencilElement {
    }
    var HTMLUiCarouselElement: {
        prototype: HTMLUiCarouselElement;
        new (): HTMLUiCarouselElement;
    };
    interface HTMLUiCheckboxElementEventMap {
        "checkboxChange": boolean;
    }
    interface HTMLUiCheckboxElement extends Components.UiCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiCheckboxElementEventMap>(type: K, listener: (this: HTMLUiCheckboxElement, ev: UiCheckboxCustomEvent<HTMLUiCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiCheckboxElementEventMap>(type: K, listener: (this: HTMLUiCheckboxElement, ev: UiCheckboxCustomEvent<HTMLUiCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiCheckboxElement: {
        prototype: HTMLUiCheckboxElement;
        new (): HTMLUiCheckboxElement;
    };
    interface HTMLUiDatePickerElementEventMap {
        "valueChange": string;
        "dateFocus": FocusEvent;
        "dateBlur": FocusEvent;
    }
    interface HTMLUiDatePickerElement extends Components.UiDatePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiDatePickerElementEventMap>(type: K, listener: (this: HTMLUiDatePickerElement, ev: UiDatePickerCustomEvent<HTMLUiDatePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiDatePickerElementEventMap>(type: K, listener: (this: HTMLUiDatePickerElement, ev: UiDatePickerCustomEvent<HTMLUiDatePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiDatePickerElement: {
        prototype: HTMLUiDatePickerElement;
        new (): HTMLUiDatePickerElement;
    };
    interface HTMLUiInputElementEventMap {
        "valueChange": string;
        "inputEvent": InputEvent;
        "inputFocus": FocusEvent;
        "inputBlur": FocusEvent;
    }
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLUiRadioElementEventMap {
        "radioChange": string;
    }
    interface HTMLUiRadioElement extends Components.UiRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiRadioElementEventMap>(type: K, listener: (this: HTMLUiRadioElement, ev: UiRadioCustomEvent<HTMLUiRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiRadioElementEventMap>(type: K, listener: (this: HTMLUiRadioElement, ev: UiRadioCustomEvent<HTMLUiRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiRadioElement: {
        prototype: HTMLUiRadioElement;
        new (): HTMLUiRadioElement;
    };
    interface HTMLUiRadioCardElementEventMap {
        "cardSelect": string;
    }
    interface HTMLUiRadioCardElement extends Components.UiRadioCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiRadioCardElementEventMap>(type: K, listener: (this: HTMLUiRadioCardElement, ev: UiRadioCardCustomEvent<HTMLUiRadioCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiRadioCardElementEventMap>(type: K, listener: (this: HTMLUiRadioCardElement, ev: UiRadioCardCustomEvent<HTMLUiRadioCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiRadioCardElement: {
        prototype: HTMLUiRadioCardElement;
        new (): HTMLUiRadioCardElement;
    };
    interface HTMLUiSelectElementEventMap {
        "valueChange": string;
        "selectFocus": FocusEvent;
        "selectBlur": FocusEvent;
    }
    interface HTMLUiSelectElement extends Components.UiSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiSelectElementEventMap>(type: K, listener: (this: HTMLUiSelectElement, ev: UiSelectCustomEvent<HTMLUiSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiSelectElementEventMap>(type: K, listener: (this: HTMLUiSelectElement, ev: UiSelectCustomEvent<HTMLUiSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiSelectElement: {
        prototype: HTMLUiSelectElement;
        new (): HTMLUiSelectElement;
    };
    interface HTMLElementTagNameMap {
        "fixed-service-flow": HTMLFixedServiceFlowElement;
        "step-catalogue": HTMLStepCatalogueElement;
        "step-confirmation": HTMLStepConfirmationElement;
        "step-contract": HTMLStepContractElement;
        "step-form": HTMLStepFormElement;
        "step-location": HTMLStepLocationElement;
        "step-order-summary": HTMLStepOrderSummaryElement;
        "step-payment": HTMLStepPaymentElement;
        "step-plans": HTMLStepPlansElement;
        "step-product-detail": HTMLStepProductDetailElement;
        "step-shipping": HTMLStepShippingElement;
        "ui-button": HTMLUiButtonElement;
        "ui-carousel": HTMLUiCarouselElement;
        "ui-checkbox": HTMLUiCheckboxElement;
        "ui-date-picker": HTMLUiDatePickerElement;
        "ui-input": HTMLUiInputElement;
        "ui-radio": HTMLUiRadioElement;
        "ui-radio-card": HTMLUiRadioCardElement;
        "ui-select": HTMLUiSelectElement;
    }
}
declare namespace LocalJSX {
    interface FixedServiceFlow {
        /**
          * Base URL for the API
         */
        "apiUrl": string;
        /**
          * Optional correlation ID for tracking
         */
        "correlationId"?: string;
        /**
          * Debug mode
          * @default false
         */
        "debug"?: boolean;
        /**
          * Google Maps API Key
         */
        "googleMapsKey": string;
        /**
          * Initial step (default: 1)
          * @default 1
         */
        "initialStep"?: FlowStep;
        /**
          * Emitted when user cancels the flow
         */
        "onFlowCancel"?: (event: FixedServiceFlowCustomEvent<void>) => void;
        /**
          * Emitted when the flow completes successfully
         */
        "onFlowComplete"?: (event: FixedServiceFlowCustomEvent<FlowCompleteEvent>) => void;
        /**
          * Emitted when an error occurs
         */
        "onFlowError"?: (event: FixedServiceFlowCustomEvent<FlowErrorEvent>) => void;
        /**
          * Emitted when step changes
         */
        "onStepChange"?: (event: FixedServiceFlowCustomEvent<StepChangeEvent>) => void;
    }
    interface StepCatalogue {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepConfirmation {
        "onBack"?: () => void;
        "onCancel"?: () => void;
        "onComplete"?: (event: FlowCompleteEvent) => void;
    }
    interface StepContract {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepForm {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepLocation {
        "googleMapsKey"?: string;
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepOrderSummary {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepPayment {
        "onBack"?: () => void;
        "onNext"?: () => void;
        "paymentIframeUrl"?: string;
    }
    interface StepPlans {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepProductDetail {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface StepShipping {
        "onBack"?: () => void;
        "onNext"?: () => void;
    }
    interface UiButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Full width button
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Loading state (shows spinner)
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when button is clicked
         */
        "onButtonClick"?: (event: UiButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button size
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * Button type attribute
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant style
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface UiCarousel {
        /**
          * Auto-play interval in milliseconds (0 = disabled)
          * @default 0
         */
        "autoplay"?: number;
        /**
          * Responsive breakpoints Default: mobile=1, tablet=2, desktop=3, large=4
          * @default [     { minWidth: 0, slidesPerView: 1 },     { minWidth: 600, slidesPerView: 2 },     { minWidth: 900, slidesPerView: 3 },     { minWidth: 1200, slidesPerView: 4 },   ]
         */
        "breakpoints"?: CarouselBreakpoint[];
        /**
          * Gap between slides in pixels
          * @default 16
         */
        "gap"?: number;
        /**
          * Enable loop/circular mode
          * @default false
         */
        "loop"?: boolean;
        /**
          * Show navigation arrows
          * @default true
         */
        "showNavigation"?: boolean;
        /**
          * Show pagination dots
          * @default true
         */
        "showPagination"?: boolean;
        /**
          * Default number of slides per view
          * @default 1
         */
        "slidesPerView"?: number;
        /**
          * Total number of items in the carousel
          * @default 0
         */
        "totalItems"?: number;
    }
    interface UiCheckbox {
        /**
          * The checkbox value
          * @default false
         */
        "checked"?: boolean;
        /**
          * Whether the checkbox is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message to display
          * @default ''
         */
        "errorMessage"?: string;
        /**
          * Whether the checkbox has an error
          * @default false
         */
        "hasError"?: boolean;
        /**
          * The checkbox label
          * @default ''
         */
        "label"?: string;
        /**
          * The checkbox name
          * @default ''
         */
        "name"?: string;
        /**
          * Event emitted when the checkbox value changes
         */
        "onCheckboxChange"?: (event: UiCheckboxCustomEvent<boolean>) => void;
    }
    interface UiDatePicker {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message to display
         */
        "error"?: string;
        /**
          * Helper text below the input
         */
        "helperText"?: string;
        /**
          * Input label
         */
        "label"?: string;
        /**
          * Maximum date (YYYY-MM-DD)
         */
        "max"?: string;
        /**
          * Minimum date (YYYY-MM-DD)
         */
        "min"?: string;
        /**
          * Input name attribute
         */
        "name"?: string;
        /**
          * Emitted on blur
         */
        "onDateBlur"?: (event: UiDatePickerCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on focus
         */
        "onDateFocus"?: (event: UiDatePickerCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when value changes
         */
        "onValueChange"?: (event: UiDatePickerCustomEvent<string>) => void;
        /**
          * Placeholder text
          * @default 'dd/mm/yyyy'
         */
        "placeholder"?: string;
        /**
          * Read-only state
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Required field
          * @default false
         */
        "required"?: boolean;
        /**
          * Current value (YYYY-MM-DD format)
          * @default ''
         */
        "value"?: string;
    }
    interface UiInput {
        /**
          * Autocomplete attribute
         */
        "autocomplete"?: string;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message to display
         */
        "error"?: string;
        /**
          * Helper text (shown when no error)
         */
        "helperText"?: string;
        /**
          * Input label text
         */
        "label"?: string;
        /**
          * Maximum length
         */
        "maxlength"?: number;
        /**
          * Minimum length
         */
        "minlength"?: number;
        /**
          * Input name attribute
         */
        "name"?: string;
        /**
          * Emitted on blur
         */
        "onInputBlur"?: (event: UiInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on input event
         */
        "onInputEvent"?: (event: UiInputCustomEvent<InputEvent>) => void;
        /**
          * Emitted on focus
         */
        "onInputFocus"?: (event: UiInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when value changes
         */
        "onValueChange"?: (event: UiInputCustomEvent<string>) => void;
        /**
          * Input pattern for validation
         */
        "pattern"?: string;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Read-only state
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Required field
          * @default false
         */
        "required"?: boolean;
        /**
          * Input type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * Current value
          * @default ''
         */
        "value"?: string;
    }
    interface UiRadio {
        /**
          * Whether this radio is selected
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Radio label text
         */
        "label"?: string;
        /**
          * Radio name (for grouping)
         */
        "name": string;
        /**
          * Emitted when radio is selected
         */
        "onRadioChange"?: (event: UiRadioCustomEvent<string>) => void;
        /**
          * Radio value
         */
        "value": string;
    }
    interface UiRadioCard {
        /**
          * Badge text (optional, e.g., "Recomendado")
         */
        "badge"?: string;
        /**
          * Card title
         */
        "cardTitle"?: string;
        /**
          * Whether this card is selected
          * @default false
         */
        "checked"?: boolean;
        /**
          * Card description
         */
        "description"?: string;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Icon name or URL (optional)
         */
        "icon"?: string;
        /**
          * Radio name (for grouping)
         */
        "name": string;
        /**
          * Emitted when card is selected
         */
        "onCardSelect"?: (event: UiRadioCardCustomEvent<string>) => void;
        /**
          * Price to display (optional)
         */
        "price"?: string;
        /**
          * Radio value
         */
        "value": string;
    }
    interface UiSelect {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message to display
         */
        "error"?: string;
        /**
          * Select label text
         */
        "label"?: string;
        /**
          * Select name attribute
         */
        "name"?: string;
        /**
          * Emitted on blur
         */
        "onSelectBlur"?: (event: UiSelectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on focus
         */
        "onSelectFocus"?: (event: UiSelectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when value changes
         */
        "onValueChange"?: (event: UiSelectCustomEvent<string>) => void;
        /**
          * Options array
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * Placeholder text
          * @default 'Seleccionar'
         */
        "placeholder"?: string;
        /**
          * Required field
          * @default false
         */
        "required"?: boolean;
        /**
          * Current selected value
          * @default ''
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "fixed-service-flow": FixedServiceFlow;
        "step-catalogue": StepCatalogue;
        "step-confirmation": StepConfirmation;
        "step-contract": StepContract;
        "step-form": StepForm;
        "step-location": StepLocation;
        "step-order-summary": StepOrderSummary;
        "step-payment": StepPayment;
        "step-plans": StepPlans;
        "step-product-detail": StepProductDetail;
        "step-shipping": StepShipping;
        "ui-button": UiButton;
        "ui-carousel": UiCarousel;
        "ui-checkbox": UiCheckbox;
        "ui-date-picker": UiDatePicker;
        "ui-input": UiInput;
        "ui-radio": UiRadio;
        "ui-radio-card": UiRadioCard;
        "ui-select": UiSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fixed-service-flow": LocalJSX.FixedServiceFlow & JSXBase.HTMLAttributes<HTMLFixedServiceFlowElement>;
            "step-catalogue": LocalJSX.StepCatalogue & JSXBase.HTMLAttributes<HTMLStepCatalogueElement>;
            "step-confirmation": LocalJSX.StepConfirmation & JSXBase.HTMLAttributes<HTMLStepConfirmationElement>;
            "step-contract": LocalJSX.StepContract & JSXBase.HTMLAttributes<HTMLStepContractElement>;
            "step-form": LocalJSX.StepForm & JSXBase.HTMLAttributes<HTMLStepFormElement>;
            "step-location": LocalJSX.StepLocation & JSXBase.HTMLAttributes<HTMLStepLocationElement>;
            "step-order-summary": LocalJSX.StepOrderSummary & JSXBase.HTMLAttributes<HTMLStepOrderSummaryElement>;
            "step-payment": LocalJSX.StepPayment & JSXBase.HTMLAttributes<HTMLStepPaymentElement>;
            "step-plans": LocalJSX.StepPlans & JSXBase.HTMLAttributes<HTMLStepPlansElement>;
            "step-product-detail": LocalJSX.StepProductDetail & JSXBase.HTMLAttributes<HTMLStepProductDetailElement>;
            "step-shipping": LocalJSX.StepShipping & JSXBase.HTMLAttributes<HTMLStepShippingElement>;
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-carousel": LocalJSX.UiCarousel & JSXBase.HTMLAttributes<HTMLUiCarouselElement>;
            "ui-checkbox": LocalJSX.UiCheckbox & JSXBase.HTMLAttributes<HTMLUiCheckboxElement>;
            "ui-date-picker": LocalJSX.UiDatePicker & JSXBase.HTMLAttributes<HTMLUiDatePickerElement>;
            "ui-input": LocalJSX.UiInput & JSXBase.HTMLAttributes<HTMLUiInputElement>;
            "ui-radio": LocalJSX.UiRadio & JSXBase.HTMLAttributes<HTMLUiRadioElement>;
            "ui-radio-card": LocalJSX.UiRadioCard & JSXBase.HTMLAttributes<HTMLUiRadioCardElement>;
            "ui-select": LocalJSX.UiSelect & JSXBase.HTMLAttributes<HTMLUiSelectElement>;
        }
    }
}
